name: Cypress Tests

on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: |
          ./node_modules/web-ext/bin/web-ext.js lint
          ./node_modules/web-ext/bin/web-ext.js build --overwrite-dest \
            --ignore-files='cypress*' \
            --ignore-files=package.json \
            --ignore-files=package-lock.json \
            --ignore-files=README.md \
            --ignore-files=test.html \
            --ignore-files=iframe.html
          cd web-ext-artifacts && unzip *

      - name: Run Cypress tests
        run: npm test
